alias connect_to_dev='ssh -i ~/.ssh/dev-identity-ecs.pem ec2-user@$(aws ec2 describe-instances --filter "Name=tag-key,Values=Name" "Name=tag-value,Values=dev-identity*" --query "Reservations[0].Instances[0].PrivateIpAddress" --output text)'
alias connect_to_test='ssh -i ~/.ssh/test-identity-ecs.pem ec2-user@$(aws ec2 describe-instances --filter "Name=tag-key,Values=Name" "Name=tag-value,Values=test-identity*" --query "Reservations[0].Instances[0].PrivateIpAddress" --output text)'
alias connect_to_stage='ssh -i ~/.ssh/stage-identity-ecs.pem ec2-user@$(aws ec2 describe-instances --filter "Name=tag-key,Values=Name" "Name=tag-value,Values=stage-identity*" --query "Reservations[0].Instances[0].PrivateIpAddress" --output text)'
alias connect_to_prod='ssh -i ~/.ssh/prod-identity-ecs.pem ec2-user@$(aws ec2 describe-instances --filter "Name=tag-key,Values=Name" "Name=tag-value,Values=prod-identity*" --query "Reservations[0].Instances[0].PrivateIpAddress" --output text)'
alias ct='sps-cli cloudtool'
#alias rolecpt='sps aws-role assume commplat-test'
alias rolecpt='leapp session start --sessionId 76b9474d-c576-408e-b000-9410666d856f'
#alias rolecpp='sps aws-role assume commplat-prod'
alias rolecpp='leapp session start --sessionId 9e8dd5da-6e43-4b28-b8e0-cd4f1eee23f2'
#alias roleidt='sps aws-role assume identity-test'
alias roleidt='leapp session start --sessionId 445c634f-658a-47a5-9d0a-6a0ab311f029'
#alias roleidp='sps aws-role assume identity-prod'
alias roleidp='leapp session start --sessionId db8e6a8c-0012-453c-bad4-6e5a741a544c'
alias tk9s='kubectl config use-context atlas-nonprod-us-east-1 && k9s'
alias pk9s='kubectl config use-context atlas-prod-us-east-1 && k9s'
