#!/bin/bash -e
ALIAS_FILE="${HOME}/.bash_aliases"
SOURCE_LINE="source ${HOME}/.bashrc.custom"

set +e
grep "${SOURCE_LINE}" ${HOME}/.bashrc > /dev/null
source_in_bashrc=$?
set -e
if [ ${source_in_bashrc} -ne 0 ] ; then
    echo "${SOURCE_LINE}" >> ${HOME}/.bashrc
fi

root_dir="$(cd $(dirname $0)/..; pwd)"

echo "# Auto-generated by dotfiles/bash/install.sh" > ${ALIAS_FILE}
find ${root_dir} -name "aliases.sh" -exec cat "{}" >> ${ALIAS_FILE} \;
